import Link from 'next/link';
import { redirect } from 'next/navigation';
import { AddressForm } from '@/components/address-form';
import { date, cop, orderStatus } from '@/lib/format';
import { serverApi, viewer } from '@/lib/server-api';
import { Order } from '@/lib/types';
export const metadata = { title: 'Mi cuenta' }; export const dynamic='force-dynamic';
interface Profile { name:string; email:string; phone?:string; addresses:Array<{id:string;label:string;line1:string;city:string;region:string;receiver:string}>; }
export default async function AccountPage() { const current=await viewer(); if(!current) redirect('/login?next=/cuenta'); const [profile,orders]=await Promise.all([serverApi<Profile>('/users/me',{},true),serverApi<Order[]>('/orders/mine',{},true)]);
 return <><section className="page-hero"><span className="eyebrow">Área personal</span><h1>Mi cuenta</h1><p>Administra tus datos, direcciones y pedidos realizados.</p></section><section className="section"><div className="container account-grid"><nav className="sidebar"><Link className="active" href="/cuenta">Resumen</Link><Link href="/tienda">Nueva compra</Link><Link href="/rastreo">Rastrear paquete</Link></nav><div><div className="form-card" style={{marginBottom:24}}><h2 style={{fontFamily:'Georgia,serif',marginTop:0}}>Perfil</h2><p><strong>{profile.name}</strong><br/>{profile.email}<br/>{profile.phone ?? 'Teléfono no registrado'}</p><h3>Direcciones registradas</h3>{profile.addresses.length ? profile.addresses.map((address)=><p key={address.id}>{address.label}: {address.line1}, {address.city} · {address.receiver}</p>) : <p className="details-copy">Aún no tienes direcciones guardadas.</p>}<AddressForm /></div><h2 style={{fontFamily:'Georgia,serif',color:'var(--forest-dark)'}}>Mis pedidos</h2><div className="orders">{orders.length ? orders.map((order)=><article className="order-card" key={order.id}><div className="order-head"><div><strong>{order.reference}</strong><p style={{margin:'6px 0',color:'var(--muted)'}}>{date(order.createdAt)} · Código: {order.trackingCode}</p></div><span className="status">{orderStatus(order.status)}</span></div><p>{order.items.map((item)=>`${item.name} × ${item.quantity}`).join(' · ')}</p><strong>Total: {cop(order.total)}</strong><div className="button-row" style={{marginTop:16}}>{order.status==='PENDING_PAYMENT' && <Link className="btn-primary" href={`/pago?orderId=${order.id}`}>Pagar pedido</Link>}<Link className="btn-secondary" href={`/rastreo?code=${order.trackingCode}`}>Rastrear</Link></div></article>) : <div className="empty">Aún no tienes pedidos.</div>}</div></div></div></section></>;
}
